### ISSUE TITLE
Deploy and task, going deeper documentation

### ISSUE THREAD

**Issue by CAberry** [glpi-project/doc-agent#3]
Hi everybody !

We've been using ocsinventory for a while now but with glpi 10 and its agent, we decided to go fully with teclib tools.
Really great work, been using glpi since version 0.85a and now on the lastest release.

I have a few questions that did not find any answer on the agent's documentation.

1 - When installing the agent, the computer name is used as the "Agent name" but when the name is changed, the old name remain in glpi. This is the same name as "device id". We use a powershell script to automate de agent installation which changes the computer name, workgroup and does a quiet install on the target without reboot. (Thus glpi-agent register with default name at first)
![image](https://user-images.githubusercontent.com/35067345/212289981-944f4c2e-bd28-44ce-b391-f9ba09ebe5b1.png)
I have search the registry and replaced all entry containing "DESKTOP-MDCQ9DU" and then changed the "agent name" and "device id" manually on glpi. If I force new inventory, the old name comes back. 

Where is that information stored? :)

2 - When creating a new packet, there is an option called "enable deploy on demand" and we can also add "target for self-service".

![image](https://user-images.githubusercontent.com/35067345/212291654-1aa968b6-ae39-45e8-a6ee-566f13db3765.png)
![image](https://user-images.githubusercontent.com/35067345/212291840-e7ca188b-d889-4a48-bd62-b3c9157e0d72.png)

What that actually means? does it mean that the package will be automatically deployed or that somewhere the users can choose in a list which software / tools they want to install on their computer?
At the beginning, I guessed that the client could see a list of available software through the client HTTP Interface.

I'm asking here those questions even tho it's not a bug or a mistake in the current documentation. It is just missing.
I know this project is pretty young and that it lacks some stuff, like how package and deploy works. I found my way to deploying stuff on computers but now I'd like to know if my users could just choose some additional software on their own.

Thank you very much for your time,
CA,

**Comment by stonebuzz** [comment]
Hi @CAberry 
You need to check ```GLPI-Agent.dump```

- Linux : ```/var/lib/glpi-agent/GLPI-Agent.dump```
- Windows : ```C:\Program Files\Glpi-Agent\var\GLPI-Agent.dump```

If you renamed computer hostname, you need to delete this file to force the agent to regenerate it with the new hostname at the next execution

"enable deploy on demand" means : Allow user to trigger deploy task if If their computer is part of ```ComputerGroup``` defined and / or if it meets the criteria (here Super-admin profile)

Best regards

**Comment by CAberry** [comment]
Hi ! Stonebuzz,

Thank you for your quick reply ! I didn't think about looking in the dump file...

As for "Allow user to trigger deploy task" does it mean that he can manually trigger the deployment for a specific package or simply that it will be part of "auto-deployment" when the agent trigger its inventory?

CA,

**Comment by CAberry** [comment]
Hello,

I have found out how to deploy package manually via the action button in the computer section.

Thank you very much for your time and help.

Best regards,
CA,
