### ISSUE TITLE
GLPI Inventory Tasks of GLPI Agent

### ISSUE THREAD

**Issue by dethorpe** [glpi-project/doc-agent#4]
Hi all, I hope I am posting this in an appropriate place. I seem to be missing some of the connective tissue between getting the GLPI server and GLPI agent to work together for network and esx inventories.

I believe my setup is 90% there, the GLPI server is running and accepting regular inventory from glpi-agents. glpi-agents have the appropriate modules installed and I can run manual esx inventories by hand (IE #glpi-ex --host xxx.xxx.x.xxx --user foo --password foo2 --directory )

I have created a task on the server with those details above that I "think" should be triggering the agent to do it's thing however that never seems to leave "prepared" and "not done yet" if I am understanding the Job execution information. I also seem to have a blind spot in the documentation here for the interrelationships between the server and agent. 

If someone has a minute to help me diagnose, I'd be happy to pay it forward with some time writing up the experience for the documentation. 

Thanks a million.

(cross post from https://github.com/glpi-project/glpi-agent/issues/389)

**Comment by g-bougard** [comment]
Hi @dethorpe 
issues are not the places to ask for help. Issues are used to notify problems with the related project, here GLPI Agent documentation.
Also, you are requesting help against GLPI Inventory and this is not directly related to this documentation.
I moved your GLPI Agent issue as a discussion as this is more appropriate, so let's talk there: https://github.com/glpi-project/glpi-agent/discussions/390
