### ISSUE TITLE
Parameter SCAN_PROFILES missing in WINDOW:Command line parameters 

### ISSUE THREAD

**Issue by Julien-Procsi** [glpi-project/doc-agent#8]
Hello, I come to point out the fact missing which misses the parameter "SCAN_PROFILES=" in the installation documentation WINDOW - Command line parameters :
![2024-01-04_10h08_26](https://github.com/glpi-project/doc-agent/assets/155624096/4ad0a28c-371b-4a04-bb12-031d45637677)

**Comment by g-bougard** [comment]
Hi @Julien-Procsi 

thank you for your contribution.
